import type { Technology } from "@/types/technology";
export const technologies: Technology[] = [
  {
    id: "openai",
    logo: "/logos/openai.svg",
    name: "OpenAI",
    slug: "openai",
    category: "ai",
    description: "Cloud language and multimodal models",
    website: "https://openai.com",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["ai"],
    recommendedFor: [],
    alternatives: ["deepseek", "anthropic", "gemini", "mistral", "groq"],
    tags: ["ai"],
    maturity: "stable",
  },
  {
    id: "deepseek",
    logo: "/logos/deepseek.svg",
    name: "DeepSeek",
    slug: "deepseek",
    category: "ai",
    description: "Cloud reasoning and language models",
    website: "https://deepseek.com",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["ai"],
    recommendedFor: [],
    alternatives: ["openai", "anthropic", "gemini", "mistral", "groq"],
    tags: ["ai"],
    maturity: "stable",
  },
  {
    id: "anthropic",
    logo: "/logos/anthropic.svg",
    name: "Anthropic",
    slug: "anthropic",
    category: "ai",
    description: "Claude language models",
    website: "https://anthropic.com",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["ai"],
    recommendedFor: [],
    alternatives: ["openai", "deepseek", "gemini", "mistral", "groq"],
    tags: ["ai"],
    maturity: "stable",
  },
  {
    id: "gemini",
    logo: "/logos/gemini.svg",
    name: "Gemini",
    slug: "gemini",
    category: "ai",
    description: "Google multimodal models",
    website: "https://ai.google.dev",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["ai"],
    recommendedFor: [],
    alternatives: ["openai", "deepseek", "anthropic", "mistral", "groq"],
    tags: ["ai"],
    maturity: "stable",
  },
  {
    id: "mistral",
    logo: "/logos/mistral.svg",
    name: "Mistral",
    slug: "mistral",
    category: "ai",
    description: "Cloud and open-weight models",
    website: "https://mistral.ai",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["ai"],
    recommendedFor: [],
    alternatives: ["openai", "deepseek", "anthropic", "gemini", "groq"],
    tags: ["ai"],
    maturity: "stable",
  },
  {
    id: "groq",
    logo: "/logos/groq.svg",
    name: "Groq",
    slug: "groq",
    category: "ai",
    description: "Hosted low-latency inference",
    website: "https://groq.com",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["ai"],
    recommendedFor: [],
    alternatives: ["openai", "deepseek", "anthropic", "gemini", "mistral"],
    tags: ["ai"],
    maturity: "stable",
  },
  {
    id: "ollama",
    logo: "/logos/ollama.svg",
    name: "Ollama",
    slug: "ollama",
    category: "ai",
    description: "Run models on your own machine",
    website: "https://ollama.com",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["ai"],
    recommendedFor: [],
    alternatives: ["openai", "deepseek", "anthropic", "gemini", "mistral"],
    tags: ["ai"],
    maturity: "stable",
  },
  {
    id: "browser-ai",
    logo: "/logos/browser-ai.svg",
    name: "Transformers.js",
    slug: "browser-ai",
    category: "ai",
    description: "Private model inference in the browser",
    website: "https://huggingface.co/docs/transformers.js",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: false,
      local: true,
      browser: true,
    },
    capabilities: ["ai"],
    recommendedFor: [],
    alternatives: ["openai", "deepseek", "anthropic", "gemini", "mistral"],
    tags: ["ai"],
    maturity: "stable",
  },
];
