import type { Technology } from "@/types/technology";
export const technologies: Technology[] = [
  {
    id: "ga4",
    logo: "/logos/ga4.svg",
    name: "Google Analytics 4",
    slug: "ga4",
    category: "analytics",
    description: "Web and app event analytics",
    website: "https://analytics.google.com",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["analytics"],
    recommendedFor: [],
    alternatives: ["clarity", "posthog", "amplitude", "mixpanel", "umami"],
    tags: ["analytics"],
    maturity: "stable",
  },
  {
    id: "clarity",
    name: "Microsoft Clarity",
    slug: "clarity",
    category: "analytics",
    description: "Session recordings and heatmaps",
    website: "https://clarity.microsoft.com",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["analytics"],
    recommendedFor: [],
    alternatives: ["ga4", "posthog", "amplitude", "mixpanel", "umami"],
    tags: ["analytics"],
    maturity: "stable",
  },
  {
    id: "posthog",
    logo: "/logos/posthog.svg",
    name: "PostHog",
    slug: "posthog",
    category: "analytics",
    description: "Product analytics and feature flags",
    website: "https://posthog.com",
    openSource: true,
    deployment: {
      saas: true,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["analytics"],
    recommendedFor: [],
    alternatives: ["ga4", "clarity", "amplitude", "mixpanel", "umami"],
    tags: ["analytics"],
    maturity: "stable",
  },
  {
    id: "amplitude",
    name: "Amplitude",
    slug: "amplitude",
    category: "analytics",
    description: "Product usage and behavioural analytics",
    website: "https://amplitude.com",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["analytics"],
    recommendedFor: [],
    alternatives: ["ga4", "clarity", "posthog", "mixpanel", "umami"],
    tags: ["analytics"],
    maturity: "stable",
  },
  {
    id: "mixpanel",
    logo: "/logos/mixpanel.svg",
    name: "Mixpanel",
    slug: "mixpanel",
    category: "analytics",
    description: "Event-based product analytics",
    website: "https://mixpanel.com",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["analytics"],
    recommendedFor: [],
    alternatives: ["ga4", "clarity", "posthog", "amplitude", "umami"],
    tags: ["analytics"],
    maturity: "stable",
  },
  {
    id: "umami",
    logo: "/logos/umami.svg",
    name: "Umami",
    slug: "umami",
    category: "analytics",
    description: "Privacy-focused website analytics",
    website: "https://umami.is",
    openSource: true,
    deployment: {
      saas: true,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["analytics"],
    recommendedFor: [],
    alternatives: ["ga4", "clarity", "posthog", "amplitude", "mixpanel"],
    tags: ["analytics"],
    maturity: "stable",
  },
  {
    id: "matomo",
    logo: "/logos/matomo.svg",
    name: "Matomo",
    slug: "matomo",
    category: "analytics",
    description: "Web analytics with data ownership",
    website: "https://matomo.org",
    openSource: true,
    deployment: {
      saas: true,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["analytics"],
    recommendedFor: [],
    alternatives: ["ga4", "clarity", "posthog", "amplitude", "mixpanel"],
    tags: ["analytics"],
    maturity: "stable",
  },
  {
    id: "plausible",
    name: "Plausible",
    slug: "plausible",
    category: "analytics",
    description: "Lightweight website analytics",
    website: "https://plausible.io",
    openSource: true,
    deployment: {
      saas: true,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["analytics"],
    recommendedFor: [],
    alternatives: ["ga4", "clarity", "posthog", "amplitude", "mixpanel"],
    tags: ["analytics"],
    maturity: "stable",
  },
];
