import type { Technology } from "@/types/technology";
export const technologies: Technology[] = [
  {
    id: "supabase-auth",
    logo: "/logos/supabase-auth.svg",
    name: "Supabase Auth",
    slug: "supabase-auth",
    category: "auth",
    description: "Identity integrated with PostgreSQL RLS",
    website: "https://supabase.com/auth",
    openSource: true,
    deployment: {
      saas: true,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["auth"],
    recommendedFor: [],
    alternatives: ["firebase-auth", "clerk", "auth0", "better-auth", "authjs"],
    tags: ["auth"],
    maturity: "stable",
    requires: ["supabase"],
  },
  {
    id: "firebase-auth",
    logo: "/logos/firebase-auth.svg",
    name: "Firebase Auth",
    slug: "firebase-auth",
    category: "auth",
    description: "Managed identity for Firebase apps",
    website: "https://firebase.google.com/docs/auth",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["auth"],
    recommendedFor: [],
    alternatives: ["supabase-auth", "clerk", "auth0", "better-auth", "authjs"],
    tags: ["auth"],
    maturity: "stable",
    requires: ["firebase"],
  },
  {
    id: "clerk",
    logo: "/logos/clerk.svg",
    name: "Clerk",
    slug: "clerk",
    category: "auth",
    description: "Managed authentication and user management",
    website: "https://clerk.com",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["auth"],
    recommendedFor: [],
    alternatives: [
      "supabase-auth",
      "firebase-auth",
      "auth0",
      "better-auth",
      "authjs",
    ],
    tags: ["auth"],
    maturity: "stable",
  },
  {
    id: "auth0",
    logo: "/logos/auth0.svg",
    name: "Auth0",
    slug: "auth0",
    category: "auth",
    description: "Managed customer identity",
    website: "https://auth0.com",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["auth"],
    recommendedFor: [],
    alternatives: [
      "supabase-auth",
      "firebase-auth",
      "clerk",
      "better-auth",
      "authjs",
    ],
    tags: ["auth"],
    maturity: "stable",
  },
  {
    id: "better-auth",
    logo: "/logos/better-auth.svg",
    name: "Better Auth",
    slug: "better-auth",
    category: "auth",
    description: "TypeScript authentication framework",
    website: "https://better-auth.com",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["auth"],
    recommendedFor: [],
    alternatives: [
      "supabase-auth",
      "firebase-auth",
      "clerk",
      "auth0",
      "authjs",
    ],
    tags: ["auth"],
    maturity: "stable",
  },
  {
    id: "authjs",
    name: "Auth.js",
    slug: "authjs",
    category: "auth",
    description: "Authentication for web applications",
    website: "https://authjs.dev",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["auth"],
    recommendedFor: [],
    alternatives: [
      "supabase-auth",
      "firebase-auth",
      "clerk",
      "auth0",
      "better-auth",
    ],
    tags: ["auth"],
    maturity: "stable",
  },
  {
    id: "workos",
    name: "WorkOS",
    slug: "workos",
    category: "auth",
    description: "Enterprise SSO and directory sync",
    website: "https://workos.com",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["auth"],
    recommendedFor: [],
    alternatives: [
      "supabase-auth",
      "firebase-auth",
      "clerk",
      "auth0",
      "better-auth",
    ],
    tags: ["auth"],
    maturity: "stable",
  },
  {
    id: "cognito",
    name: "Cognito",
    slug: "cognito",
    category: "auth",
    description: "AWS managed user identity",
    website: "https://aws.amazon.com/cognito",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["auth"],
    recommendedFor: [],
    alternatives: [
      "supabase-auth",
      "firebase-auth",
      "clerk",
      "auth0",
      "better-auth",
    ],
    tags: ["auth"],
    maturity: "stable",
  },
  {
    id: "keycloak",
    logo: "/logos/keycloak.svg",
    name: "Keycloak",
    slug: "keycloak",
    category: "auth",
    description: "Self-hosted identity and access management",
    website: "https://keycloak.org",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["auth"],
    recommendedFor: [],
    alternatives: [
      "supabase-auth",
      "firebase-auth",
      "clerk",
      "auth0",
      "better-auth",
    ],
    tags: ["auth"],
    maturity: "stable",
  },
  {
    id: "ory",
    logo: "/logos/ory.svg",
    name: "Ory",
    slug: "ory",
    category: "auth",
    description: "Composable identity infrastructure",
    website: "https://ory.sh",
    openSource: true,
    deployment: {
      saas: true,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["auth"],
    recommendedFor: [],
    alternatives: [
      "supabase-auth",
      "firebase-auth",
      "clerk",
      "auth0",
      "better-auth",
    ],
    tags: ["auth"],
    maturity: "stable",
  },
];
