import type { Technology } from "@/types/technology";

/** One catalogue row for a CI host or a delivery controller. */
function entry(
  item: Pick<
    Technology,
    "id" | "name" | "slug" | "description" | "website" | "alternatives"
  > & {
    logo?: string;
    kind: "ci" | "cd";
    openSource?: boolean;
    saas?: boolean;
    selfHosted?: boolean;
    local?: boolean;
    requires?: string[];
  },
): Technology {
  return {
    id: item.id,
    logo: item.logo,
    name: item.name,
    slug: item.slug,
    category: item.kind,
    description: item.description,
    website: item.website,
    openSource: item.openSource ?? false,
    deployment: {
      saas: item.saas ?? false,
      selfHosted: item.selfHosted ?? false,
      local: item.local ?? false,
      browser: false,
    },
    capabilities: [item.kind],
    recommendedFor: [],
    alternatives: item.alternatives,
    requires: item.requires,
    tags: ["automation", item.kind],
    maturity: "stable",
  };
}

export const technologies: Technology[] = [
  entry({
    id: "github-actions",
    logo: "/logos/github-actions.svg",
    name: "GitHub Actions",
    slug: "github-actions",
    kind: "ci",
    description: "Workflows on GitHub for verify and release",
    website: "https://github.com/features/actions",
    saas: true,
    alternatives: [
      "gitlab-ci",
      "circleci",
      "jenkins",
      "azure-pipelines",
      "buildkite",
    ],
  }),
  entry({
    id: "gitlab-ci",
    logo: "/logos/gitlab.svg",
    name: "GitLab CI",
    slug: "gitlab-ci",
    kind: "ci",
    description: "Pipelines defined in the GitLab repository",
    website: "https://docs.gitlab.com/ci/",
    openSource: true,
    saas: true,
    selfHosted: true,
    alternatives: [
      "github-actions",
      "jenkins",
      "woodpecker",
      "teamcity",
      "circleci",
    ],
  }),
  entry({
    id: "teamcity",
    logo: "/logos/teamcity.svg",
    name: "TeamCity",
    slug: "teamcity",
    kind: "ci",
    description: "JetBrains build server and pipelines",
    website: "https://www.jetbrains.com/teamcity/",
    saas: true,
    selfHosted: true,
    local: true,
    alternatives: ["jenkins", "github-actions", "gitlab-ci", "azure-pipelines"],
  }),
  entry({
    id: "jenkins",
    logo: "/logos/jenkins.svg",
    name: "Jenkins",
    slug: "jenkins",
    kind: "ci",
    description: "Self-hosted automation server",
    website: "https://www.jenkins.io",
    openSource: true,
    selfHosted: true,
    local: true,
    alternatives: ["teamcity", "woodpecker", "gitlab-ci", "github-actions"],
  }),
  entry({
    id: "circleci",
    logo: "/logos/circleci.svg",
    name: "CircleCI",
    slug: "circleci",
    kind: "ci",
    description: "Hosted pipelines for build and test",
    website: "https://circleci.com",
    saas: true,
    alternatives: [
      "github-actions",
      "buildkite",
      "gitlab-ci",
      "azure-pipelines",
    ],
  }),
  entry({
    id: "buildkite",
    logo: "/logos/buildkite.svg",
    name: "Buildkite",
    slug: "buildkite",
    kind: "ci",
    description: "Pipelines that run on your own agents",
    website: "https://buildkite.com",
    saas: true,
    selfHosted: true,
    alternatives: ["github-actions", "circleci", "jenkins", "tekton"],
  }),
  entry({
    id: "azure-pipelines",
    logo: "/logos/azure.svg",
    name: "Azure Pipelines",
    slug: "azure-pipelines",
    kind: "ci",
    description: "Azure DevOps build and release",
    website: "https://azure.microsoft.com/products/devops/pipelines/",
    saas: true,
    alternatives: ["github-actions", "gitlab-ci", "teamcity", "codepipeline"],
  }),
  entry({
    id: "bitbucket-pipelines",
    logo: "/logos/bitbucket.svg",
    name: "Bitbucket Pipelines",
    slug: "bitbucket-pipelines",
    kind: "ci",
    description: "Pipelines hosted with Bitbucket",
    website: "https://bitbucket.org/product/features/pipelines",
    saas: true,
    alternatives: ["github-actions", "gitlab-ci", "circleci", "jenkins"],
  }),
  entry({
    id: "woodpecker",
    name: "Woodpecker CI",
    slug: "woodpecker",
    kind: "ci",
    description: "Self-hosted pipelines for a Git repository",
    website: "https://woodpecker-ci.org",
    openSource: true,
    selfHosted: true,
    local: true,
    alternatives: ["drone", "jenkins", "gitlab-ci", "tekton"],
  }),
  entry({
    id: "drone",
    name: "Drone CI",
    slug: "drone",
    kind: "ci",
    description: "Container-native pipelines for a Git repository",
    website: "https://www.drone.io",
    openSource: true,
    selfHosted: true,
    local: true,
    alternatives: ["woodpecker", "tekton", "gitlab-ci", "github-actions"],
  }),
  entry({
    id: "earthly",
    name: "Earthly",
    slug: "earthly",
    kind: "ci",
    description: "Repeatable builds that any CI host can call",
    website: "https://earthly.dev",
    openSource: true,
    selfHosted: true,
    local: true,
    alternatives: ["dagger", "tekton", "github-actions", "buildkite"],
  }),
  entry({
    id: "cloud-build",
    logo: "/logos/gcp.svg",
    name: "Cloud Build",
    slug: "cloud-build",
    kind: "ci",
    description: "Build steps on Google Cloud",
    website: "https://cloud.google.com/build",
    saas: true,
    alternatives: [
      "codepipeline",
      "github-actions",
      "tekton",
      "azure-pipelines",
    ],
  }),
  entry({
    id: "codepipeline",
    logo: "/logos/aws.svg",
    name: "AWS CodePipeline",
    slug: "codepipeline",
    kind: "ci",
    description: "AWS pipeline for build and release",
    website: "https://aws.amazon.com/codepipeline/",
    saas: true,
    alternatives: [
      "cloud-build",
      "github-actions",
      "azure-pipelines",
      "tekton",
    ],
  }),
  entry({
    id: "tekton",
    logo: "/logos/tekton.svg",
    name: "Tekton",
    slug: "tekton",
    kind: "ci",
    description: "Pipelines that run on Kubernetes",
    website: "https://tekton.dev",
    openSource: true,
    selfHosted: true,
    local: true,
    alternatives: ["jenkins", "dagger", "github-actions", "woodpecker"],
  }),
  entry({
    id: "dagger",
    name: "Dagger",
    slug: "dagger",
    kind: "ci",
    description: "Pipelines as code, called from any CI host",
    website: "https://dagger.io",
    openSource: true,
    selfHosted: true,
    local: true,
    alternatives: ["earthly", "tekton", "github-actions", "buildkite"],
  }),
  entry({
    id: "harness",
    name: "Harness",
    slug: "harness",
    kind: "cd",
    description: "Continuous delivery with approvals and rollbacks",
    website: "https://www.harness.io",
    saas: true,
    selfHosted: true,
    alternatives: ["spinnaker", "octopus", "argocd"],
  }),
  entry({
    id: "argocd",
    logo: "/logos/argo.svg",
    name: "Argo CD",
    slug: "argocd",
    kind: "cd",
    description: "GitOps delivery for Kubernetes",
    website: "https://argo-cd.readthedocs.io",
    openSource: true,
    selfHosted: true,
    local: true,
    requires: ["kubernetes"],
    alternatives: ["flux", "spinnaker", "octopus", "harness"],
  }),
  entry({
    id: "flux",
    logo: "/logos/flux.svg",
    name: "Flux CD",
    slug: "flux",
    kind: "cd",
    description: "GitOps toolkit that reconciles Kubernetes",
    website: "https://fluxcd.io",
    openSource: true,
    selfHosted: true,
    local: true,
    requires: ["kubernetes"],
    alternatives: ["argocd", "spinnaker", "octopus", "harness"],
  }),
  entry({
    id: "argo-rollouts",
    logo: "/logos/argo.svg",
    name: "Argo Rollouts",
    slug: "argo-rollouts",
    kind: "cd",
    description: "Canary and blue-green releases on Kubernetes",
    website: "https://argo-rollouts.readthedocs.io",
    openSource: true,
    selfHosted: true,
    local: true,
    requires: ["kubernetes"],
    alternatives: ["argocd", "flux", "spinnaker"],
  }),
  entry({
    id: "spinnaker",
    logo: "/logos/spinnaker.svg",
    name: "Spinnaker",
    slug: "spinnaker",
    kind: "cd",
    description: "Multi-cloud delivery and release",
    website: "https://spinnaker.io",
    openSource: true,
    selfHosted: true,
    local: true,
    alternatives: ["argocd", "flux", "octopus", "harness"],
  }),
  entry({
    id: "octopus",
    logo: "/logos/octopus.svg",
    name: "Octopus Deploy",
    slug: "octopus",
    kind: "cd",
    description: "Promote one build through environments",
    website: "https://octopus.com",
    saas: true,
    selfHosted: true,
    alternatives: ["spinnaker", "argocd", "flux", "harness"],
  }),
];
