import type { Technology } from "@/types/technology";
export const technologies: Technology[] = [
  {
    id: "zod",
    logo: "/logos/zod.svg",
    name: "Zod",
    slug: "zod",
    category: "backend-library",
    description: "TypeScript-first schema validation",
    website: "https://zod.dev",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["backend-library"],
    recommendedFor: [],
    alternatives: ["valibot", "yup", "arktype", "supabase-js", "supabase-ssr"],
    tags: ["backend-library"],
    maturity: "stable",
  },
  {
    id: "valibot",
    name: "Valibot",
    slug: "valibot",
    category: "backend-library",
    description: "Modular schema validation",
    website: "https://valibot.dev",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["backend-library"],
    recommendedFor: [],
    alternatives: ["zod", "yup", "arktype", "supabase-js", "supabase-ssr"],
    tags: ["backend-library"],
    maturity: "stable",
  },
  {
    id: "yup",
    name: "Yup",
    slug: "yup",
    category: "backend-library",
    description: "Object schema validation",
    website: "https://github.com/jquense/yup",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["backend-library"],
    recommendedFor: [],
    alternatives: ["zod", "valibot", "arktype", "supabase-js", "supabase-ssr"],
    tags: ["backend-library"],
    maturity: "stable",
  },
  {
    id: "arktype",
    name: "ArkType",
    slug: "arktype",
    category: "backend-library",
    description: "Type-safe runtime validation",
    website: "https://arktype.io",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["backend-library"],
    recommendedFor: [],
    alternatives: ["zod", "valibot", "yup", "supabase-js", "supabase-ssr"],
    tags: ["backend-library"],
    maturity: "stable",
  },
  {
    id: "supabase-js",
    logo: "/logos/supabase-js.svg",
    name: "Supabase JS",
    slug: "supabase-js",
    category: "backend-library",
    description: "JavaScript client for Supabase",
    website: "https://supabase.com/docs/reference/javascript",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["backend-library"],
    recommendedFor: [],
    alternatives: ["zod", "valibot", "yup", "arktype", "supabase-ssr"],
    tags: ["backend-library"],
    maturity: "stable",
    requires: ["supabase"],
  },
  {
    id: "supabase-ssr",
    logo: "/logos/supabase-ssr.svg",
    name: "Supabase SSR",
    slug: "supabase-ssr",
    category: "backend-library",
    description: "Cookie-based server authentication",
    website: "https://supabase.com/docs/guides/auth/server-side",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["backend-library"],
    recommendedFor: [],
    alternatives: ["zod", "valibot", "yup", "arktype", "supabase-js"],
    tags: ["backend-library"],
    maturity: "stable",
    requires: ["supabase-js"],
  },
];
