import type { Technology } from "@/types/technology";
export const technologies: Technology[] = [
  {
    id: "supabase",
    logo: "/logos/supabase.svg",
    name: "Supabase",
    slug: "supabase",
    category: "backend",
    description: "PostgreSQL, Auth, Storage and Realtime",
    website: "https://supabase.com",
    openSource: true,
    deployment: {
      saas: true,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: [
      "postgresql",
      "authentication",
      "storage",
      "realtime",
      "database-api",
      "row-level-security",
    ],
    recommendedFor: [],
    alternatives: ["firebase", "appwrite", "convex", "pocketbase", "nhost"],
    tags: ["backend"],
    maturity: "stable",
    implies: ["postgresql"],
  },
  {
    id: "firebase",
    logo: "/logos/firebase.svg",
    name: "Firebase",
    slug: "firebase",
    category: "backend",
    description: "Managed backend services from Google",
    website: "https://firebase.google.com",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["backend"],
    recommendedFor: [],
    alternatives: ["supabase", "appwrite", "convex", "pocketbase", "nhost"],
    tags: ["backend"],
    maturity: "stable",
  },
  {
    id: "appwrite",
    logo: "/logos/appwrite.svg",
    name: "Appwrite",
    slug: "appwrite",
    category: "backend",
    description: "Auth, database, functions and storage",
    website: "https://appwrite.io",
    openSource: true,
    deployment: {
      saas: true,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["backend"],
    recommendedFor: [],
    alternatives: ["supabase", "firebase", "convex", "pocketbase", "nhost"],
    tags: ["backend"],
    maturity: "stable",
  },
  {
    id: "convex",
    logo: "/logos/convex.svg",
    name: "Convex",
    slug: "convex",
    category: "backend",
    description: "Reactive backend for TypeScript",
    website: "https://convex.dev",
    openSource: true,
    deployment: {
      saas: true,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["backend"],
    recommendedFor: [],
    alternatives: ["supabase", "firebase", "appwrite", "pocketbase", "nhost"],
    tags: ["backend"],
    maturity: "stable",
  },
  {
    id: "pocketbase",
    logo: "/logos/pocketbase.svg",
    name: "PocketBase",
    slug: "pocketbase",
    category: "backend",
    description: "Embedded backend in a single executable",
    website: "https://pocketbase.io",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["backend"],
    recommendedFor: [],
    alternatives: ["supabase", "firebase", "appwrite", "convex", "nhost"],
    tags: ["backend"],
    maturity: "stable",
  },
  {
    id: "nhost",
    logo: "/logos/nhost.svg",
    name: "Nhost",
    slug: "nhost",
    category: "backend",
    description: "PostgreSQL and GraphQL backend",
    website: "https://nhost.io",
    openSource: true,
    deployment: {
      saas: true,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["backend"],
    recommendedFor: [],
    alternatives: ["supabase", "firebase", "appwrite", "convex", "pocketbase"],
    tags: ["backend"],
    maturity: "stable",
  },
];
