import type { Technology } from "@/types/technology";
export const technologies: Technology[] = [
  {
    id: "postgresql",
    logo: "/logos/postgresql.svg",
    name: "PostgreSQL",
    slug: "postgresql",
    category: "database",
    description: "Relational database with rich SQL",
    website: "https://postgresql.org",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["database"],
    recommendedFor: [],
    alternatives: ["mysql", "mongodb", "firestore", "sqlite", "neon"],
    tags: ["database"],
    maturity: "stable",
  },
  {
    id: "mysql",
    logo: "/logos/mysql.svg",
    name: "MySQL",
    slug: "mysql",
    category: "database",
    description: "Widely used relational database",
    website: "https://mysql.com",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["database"],
    recommendedFor: [],
    alternatives: ["postgresql", "mongodb", "firestore", "sqlite", "neon"],
    tags: ["database"],
    maturity: "stable",
  },
  {
    id: "mongodb",
    logo: "/logos/mongodb.svg",
    name: "MongoDB",
    slug: "mongodb",
    category: "database",
    description: "Document-oriented database",
    website: "https://mongodb.com",
    openSource: true,
    deployment: {
      saas: true,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["database"],
    recommendedFor: [],
    alternatives: ["postgresql", "mysql", "firestore", "sqlite", "neon"],
    tags: ["database"],
    maturity: "stable",
  },
  {
    id: "firestore",
    logo: "/logos/firestore.svg",
    name: "Firestore",
    slug: "firestore",
    category: "database",
    description: "Managed document database",
    website: "https://firebase.google.com/docs/firestore",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["database"],
    recommendedFor: [],
    alternatives: ["postgresql", "mysql", "mongodb", "sqlite", "neon"],
    tags: ["database"],
    maturity: "stable",
  },
  {
    id: "sqlite",
    logo: "/logos/sqlite.svg",
    name: "SQLite",
    slug: "sqlite",
    category: "database",
    description: "Embedded SQL database",
    website: "https://sqlite.org",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["database"],
    recommendedFor: [],
    alternatives: ["postgresql", "mysql", "mongodb", "firestore", "neon"],
    tags: ["database"],
    maturity: "stable",
  },
  {
    id: "neon",
    logo: "/logos/neon.svg",
    name: "Neon",
    slug: "neon",
    category: "database",
    description: "Managed serverless PostgreSQL",
    website: "https://neon.com",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: true,
      browser: false,
    },
    capabilities: ["database"],
    recommendedFor: [],
    alternatives: ["postgresql", "mysql", "mongodb", "firestore", "sqlite"],
    tags: ["database"],
    maturity: "stable",
  },
  {
    id: "d1",
    logo: "/logos/d1.svg",
    name: "Cloudflare D1",
    slug: "d1",
    category: "database",
    description: "Serverless SQL at Cloudflare",
    website: "https://developers.cloudflare.com/d1",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["database"],
    recommendedFor: [],
    alternatives: ["postgresql", "mysql", "mongodb", "firestore", "sqlite"],
    tags: ["database"],
    maturity: "stable",
  },
  {
    id: "turso",
    logo: "/logos/turso.svg",
    name: "Turso",
    slug: "turso",
    category: "database",
    description: "Distributed SQLite-compatible database",
    website: "https://turso.tech",
    openSource: true,
    deployment: {
      saas: true,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["database"],
    recommendedFor: [],
    alternatives: ["postgresql", "mysql", "mongodb", "firestore", "sqlite"],
    tags: ["database"],
    maturity: "stable",
  },
];
