import type { Technology } from "@/types/technology";
export const technologies: Technology[] = [
  {
    id: "vercel",
    logo: "/logos/vercel.svg",
    name: "Vercel",
    slug: "vercel",
    category: "deployment",
    description: "Managed hosting for web applications",
    website: "https://vercel.com",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["deployment"],
    recommendedFor: [],
    alternatives: ["cloudflare", "netlify", "render", "railway", "fly"],
    tags: ["deployment"],
    maturity: "stable",
  },
  {
    id: "cloudflare",
    logo: "/logos/cloudflare.svg",
    name: "Cloudflare",
    slug: "cloudflare",
    category: "deployment",
    description: "Edge hosting, DNS and CDN",
    website: "https://cloudflare.com",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["deployment"],
    recommendedFor: [],
    alternatives: ["vercel", "netlify", "render", "railway", "fly"],
    tags: ["deployment"],
    maturity: "stable",
  },
  {
    id: "netlify",
    logo: "/logos/netlify.svg",
    name: "Netlify",
    slug: "netlify",
    category: "deployment",
    description: "Managed web application hosting",
    website: "https://netlify.com",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["deployment"],
    recommendedFor: [],
    alternatives: ["vercel", "cloudflare", "render", "railway", "fly"],
    tags: ["deployment"],
    maturity: "stable",
  },
  {
    id: "render",
    logo: "/logos/render.svg",
    name: "Render",
    slug: "render",
    category: "deployment",
    description: "Managed apps and services",
    website: "https://render.com",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["deployment"],
    recommendedFor: [],
    alternatives: ["vercel", "cloudflare", "netlify", "railway", "fly"],
    tags: ["deployment"],
    maturity: "stable",
  },
  {
    id: "railway",
    logo: "/logos/railway.svg",
    name: "Railway",
    slug: "railway",
    category: "deployment",
    description: "Application and database hosting",
    website: "https://railway.com",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["deployment"],
    recommendedFor: [],
    alternatives: ["vercel", "cloudflare", "netlify", "render", "fly"],
    tags: ["deployment"],
    maturity: "stable",
  },
  {
    id: "fly",
    logo: "/logos/fly.svg",
    name: "Fly.io",
    slug: "fly",
    category: "deployment",
    description: "Applications close to users",
    website: "https://fly.io",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["deployment"],
    recommendedFor: [],
    alternatives: ["vercel", "cloudflare", "netlify", "render", "railway"],
    tags: ["deployment"],
    maturity: "stable",
  },
  {
    id: "aws",
    logo: "/logos/aws.svg",
    name: "AWS",
    slug: "aws",
    category: "deployment",
    description: "Cloud compute and infrastructure",
    website: "https://aws.amazon.com",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["deployment"],
    recommendedFor: [],
    alternatives: ["gcp", "azure", "vercel", "cloudflare", "netlify"],
    tags: ["deployment"],
    maturity: "stable",
  },
  {
    id: "gcp",
    logo: "/logos/gcp.svg",
    name: "Google Cloud",
    slug: "gcp",
    category: "deployment",
    description: "Google cloud compute and infrastructure",
    website: "https://cloud.google.com",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["deployment"],
    recommendedFor: [],
    alternatives: ["aws", "azure", "vercel", "cloudflare", "kubernetes"],
    tags: ["deployment"],
    maturity: "stable",
  },
  {
    id: "azure",
    logo: "/logos/azure.svg",
    name: "Azure",
    slug: "azure",
    category: "deployment",
    description: "Microsoft cloud compute and infrastructure",
    website: "https://azure.microsoft.com",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["deployment"],
    recommendedFor: [],
    alternatives: ["aws", "gcp", "vercel", "cloudflare", "kubernetes"],
    tags: ["deployment"],
    maturity: "stable",
  },
  {
    id: "firebase-hosting",
    logo: "/logos/firebase-hosting.svg",
    name: "Firebase Hosting",
    slug: "firebase-hosting",
    category: "deployment",
    description: "Managed Firebase application hosting",
    website: "https://firebase.google.com/docs/hosting",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["deployment"],
    recommendedFor: [],
    alternatives: ["vercel", "cloudflare", "netlify", "render", "railway"],
    tags: ["deployment"],
    maturity: "stable",
  },
  {
    id: "kubernetes",
    logo: "/logos/kubernetes.svg",
    name: "Kubernetes",
    slug: "kubernetes",
    category: "deployment",
    description: "Container orchestration on your infrastructure",
    website: "https://kubernetes.io",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["deployment"],
    recommendedFor: [],
    alternatives: ["vercel", "cloudflare", "netlify", "render", "railway"],
    tags: ["deployment"],
    maturity: "stable",
  },
];
