import type { Technology } from "@/types/technology";
export const technologies: Technology[] = [
  {
    id: "tauri",
    logo: "/logos/tauri.svg",
    name: "Tauri",
    slug: "tauri",
    category: "desktop",
    description: "Desktop apps with a Rust core",
    website: "https://tauri.app",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["desktop"],
    recommendedFor: [],
    alternatives: ["electron", "neutralino"],
    tags: ["desktop"],
    maturity: "stable",
  },
  {
    id: "electron",
    logo: "/logos/electron.svg",
    name: "Electron",
    slug: "electron",
    category: "desktop",
    description: "Desktop apps with Chromium and Node.js",
    website: "https://electronjs.org",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["desktop"],
    recommendedFor: [],
    alternatives: ["tauri", "neutralino"],
    tags: ["desktop"],
    maturity: "stable",
  },
  {
    id: "neutralino",
    name: "Neutralino",
    slug: "neutralino",
    category: "desktop",
    description: "Lightweight desktop app runtime",
    website: "https://neutralino.js.org",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["desktop"],
    recommendedFor: [],
    alternatives: ["tauri", "electron"],
    tags: ["desktop"],
    maturity: "stable",
  },
];
