import type { Technology } from "@/types/technology";
export const technologies: Technology[] = [
  {
    id: "resend",
    logo: "/logos/resend.svg",
    name: "Resend",
    slug: "resend",
    category: "email",
    description: "Transactional email API",
    website: "https://resend.com",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["email"],
    recommendedFor: [],
    alternatives: ["postmark", "sendgrid", "mailgun", "ses"],
    tags: ["email"],
    maturity: "stable",
  },
  {
    id: "postmark",
    name: "Postmark",
    slug: "postmark",
    category: "email",
    description: "Transactional email delivery",
    website: "https://postmarkapp.com",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["email"],
    recommendedFor: [],
    alternatives: ["resend", "sendgrid", "mailgun", "ses"],
    tags: ["email"],
    maturity: "stable",
  },
  {
    id: "sendgrid",
    name: "SendGrid",
    slug: "sendgrid",
    category: "email",
    description: "Email delivery platform",
    website: "https://sendgrid.com",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["email"],
    recommendedFor: [],
    alternatives: ["resend", "postmark", "mailgun", "ses"],
    tags: ["email"],
    maturity: "stable",
  },
  {
    id: "mailgun",
    logo: "/logos/mailgun.svg",
    name: "Mailgun",
    slug: "mailgun",
    category: "email",
    description: "Email APIs and delivery",
    website: "https://mailgun.com",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["email"],
    recommendedFor: [],
    alternatives: ["resend", "postmark", "sendgrid", "ses"],
    tags: ["email"],
    maturity: "stable",
  },
  {
    id: "ses",
    name: "Amazon SES",
    slug: "ses",
    category: "email",
    description: "AWS email delivery",
    website: "https://aws.amazon.com/ses",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["email"],
    recommendedFor: [],
    alternatives: ["resend", "postmark", "sendgrid", "mailgun"],
    tags: ["email"],
    maturity: "stable",
  },
];
