import type { Technology } from "@/types/technology";
export const technologies: Technology[] = [
  {
    id: "flagsmith",
    logo: "/logos/flagsmith.svg",
    name: "Flagsmith",
    slug: "flagsmith",
    category: "feature-flags",
    description: "Feature flags and remote configuration",
    website: "https://flagsmith.com",
    openSource: true,
    deployment: {
      saas: true,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["feature-flags"],
    recommendedFor: [],
    alternatives: [
      "launchdarkly",
      "growthbook",
      "unleash",
      "configcat",
      "openfeature",
    ],
    tags: ["feature-flags"],
    maturity: "stable",
  },
  {
    id: "launchdarkly",
    logo: "/logos/launchdarkly.svg",
    name: "LaunchDarkly",
    slug: "launchdarkly",
    category: "feature-flags",
    description: "Managed feature delivery",
    website: "https://launchdarkly.com",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["feature-flags"],
    recommendedFor: [],
    alternatives: [
      "flagsmith",
      "growthbook",
      "unleash",
      "configcat",
      "openfeature",
    ],
    tags: ["feature-flags"],
    maturity: "stable",
  },
  {
    id: "growthbook",
    logo: "/logos/growthbook.svg",
    name: "GrowthBook",
    slug: "growthbook",
    category: "feature-flags",
    description: "Feature flags and experimentation",
    website: "https://growthbook.io",
    openSource: true,
    deployment: {
      saas: true,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["feature-flags"],
    recommendedFor: [],
    alternatives: [
      "flagsmith",
      "launchdarkly",
      "unleash",
      "configcat",
      "openfeature",
    ],
    tags: ["feature-flags"],
    maturity: "stable",
  },
  {
    id: "unleash",
    logo: "/logos/unleash.svg",
    name: "Unleash",
    slug: "unleash",
    category: "feature-flags",
    description: "Open-source feature management",
    website: "https://getunleash.io",
    openSource: true,
    deployment: {
      saas: true,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["feature-flags"],
    recommendedFor: [],
    alternatives: [
      "flagsmith",
      "launchdarkly",
      "growthbook",
      "configcat",
      "openfeature",
    ],
    tags: ["feature-flags"],
    maturity: "stable",
  },
  {
    id: "configcat",
    logo: "/logos/configcat.svg",
    name: "ConfigCat",
    slug: "configcat",
    category: "feature-flags",
    description: "Hosted feature flag service",
    website: "https://configcat.com",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["feature-flags"],
    recommendedFor: [],
    alternatives: [
      "flagsmith",
      "launchdarkly",
      "growthbook",
      "unleash",
      "openfeature",
    ],
    tags: ["feature-flags"],
    maturity: "stable",
  },
  {
    id: "openfeature",
    logo: "/logos/openfeature.svg",
    name: "OpenFeature",
    slug: "openfeature",
    category: "feature-flags",
    description: "Vendor-neutral feature flag API",
    website: "https://openfeature.dev",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["feature-flags"],
    recommendedFor: [],
    alternatives: [
      "flagsmith",
      "launchdarkly",
      "growthbook",
      "unleash",
      "configcat",
    ],
    tags: ["feature-flags"],
    maturity: "stable",
  },
];
