import type { Technology } from "@/types/technology";
export const technologies: Technology[] = [
  {
    id: "nextjs",
    logo: "/logos/nextjs.svg",
    name: "Next.js",
    slug: "nextjs",
    category: "frontend",
    description: "React framework with App Router and server rendering",
    website: "https://nextjs.org",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["frontend"],
    recommendedFor: [],
    alternatives: [
      "react-router",
      "tanstack-start",
      "nuxt",
      "sveltekit",
      "astro",
    ],
    tags: ["frontend"],
    maturity: "stable",
  },
  {
    id: "react-router",
    logo: "/logos/react-router.svg",
    name: "React Router",
    slug: "react-router",
    category: "frontend",
    description: "React routing and full-stack framework",
    website: "https://reactrouter.com",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["frontend"],
    recommendedFor: [],
    alternatives: ["nextjs", "tanstack-start", "nuxt", "sveltekit", "astro"],
    tags: ["frontend"],
    maturity: "stable",
  },
  {
    id: "tanstack-start",
    logo: "/logos/tanstack-start.svg",
    name: "TanStack Start",
    slug: "tanstack-start",
    category: "frontend",
    description: "Type-safe full-stack React applications",
    website: "https://tanstack.com/start",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["frontend"],
    recommendedFor: [],
    alternatives: ["nextjs", "react-router", "nuxt", "sveltekit", "astro"],
    tags: ["frontend"],
    maturity: "stable",
  },
  {
    id: "nuxt",
    logo: "/logos/nuxt.svg",
    name: "Nuxt",
    slug: "nuxt",
    category: "frontend",
    description: "Full-stack Vue applications",
    website: "https://nuxt.com",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["frontend"],
    recommendedFor: [],
    alternatives: [
      "nextjs",
      "react-router",
      "tanstack-start",
      "sveltekit",
      "astro",
    ],
    tags: ["frontend"],
    maturity: "stable",
  },
  {
    id: "sveltekit",
    logo: "/logos/sveltekit.svg",
    name: "SvelteKit",
    slug: "sveltekit",
    category: "frontend",
    description: "Full-stack framework for Svelte",
    website: "https://svelte.dev",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["frontend"],
    recommendedFor: [],
    alternatives: ["nextjs", "react-router", "tanstack-start", "nuxt", "astro"],
    tags: ["frontend"],
    maturity: "stable",
  },
  {
    id: "astro",
    logo: "/logos/astro.svg",
    name: "Astro",
    slug: "astro",
    category: "frontend",
    description: "Content-focused sites with islands",
    website: "https://astro.build",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["frontend"],
    recommendedFor: [],
    alternatives: [
      "nextjs",
      "react-router",
      "tanstack-start",
      "nuxt",
      "sveltekit",
    ],
    tags: ["frontend"],
    maturity: "stable",
  },
  {
    id: "angular",
    logo: "/logos/angular.svg",
    name: "Angular",
    slug: "angular",
    category: "frontend",
    description: "Structured framework for web applications",
    website: "https://angular.dev",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["frontend"],
    recommendedFor: [],
    alternatives: [
      "nextjs",
      "react-router",
      "tanstack-start",
      "nuxt",
      "sveltekit",
    ],
    tags: ["frontend"],
    maturity: "stable",
  },
];
