import type { Technology } from "@/types/technology";
export const technologies: Technology[] = [
  {
    id: "tailwind",
    logo: "/logos/tailwind.svg",
    name: "Tailwind CSS",
    slug: "tailwind",
    category: "frontend-library",
    description: "Utility-first CSS styling",
    website: "https://tailwindcss.com",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["frontend-library"],
    recommendedFor: [],
    alternatives: [
      "css-modules",
      "panda",
      "vanilla-extract",
      "zustand",
      "redux",
    ],
    tags: ["frontend-library"],
    maturity: "stable",
  },
  {
    id: "css-modules",
    logo: "/logos/css-modules.svg",
    name: "CSS Modules",
    slug: "css-modules",
    category: "frontend-library",
    description: "Locally scoped component CSS",
    website: "https://github.com/css-modules/css-modules",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["frontend-library"],
    recommendedFor: [],
    alternatives: ["tailwind", "panda", "vanilla-extract", "zustand", "redux"],
    tags: ["frontend-library"],
    maturity: "stable",
  },
  {
    id: "panda",
    logo: "/logos/panda.svg",
    name: "Panda CSS",
    slug: "panda",
    category: "frontend-library",
    description: "Build-time type-safe CSS",
    website: "https://panda-css.com",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["frontend-library"],
    recommendedFor: [],
    alternatives: [
      "tailwind",
      "css-modules",
      "vanilla-extract",
      "zustand",
      "redux",
    ],
    tags: ["frontend-library"],
    maturity: "stable",
  },
  {
    id: "vanilla-extract",
    logo: "/logos/vanilla-extract.svg",
    name: "vanilla-extract",
    slug: "vanilla-extract",
    category: "frontend-library",
    description: "Zero-runtime styles in TypeScript",
    website: "https://vanilla-extract.style",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["frontend-library"],
    recommendedFor: [],
    alternatives: ["tailwind", "css-modules", "panda", "zustand", "redux"],
    tags: ["frontend-library"],
    maturity: "stable",
  },
  {
    id: "zustand",
    logo: "/logos/zustand.svg",
    name: "Zustand",
    slug: "zustand",
    category: "frontend-library",
    description: "Small, flexible client state store",
    website: "https://zustand.docs.pmnd.rs",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["frontend-library"],
    recommendedFor: [],
    alternatives: [
      "tailwind",
      "css-modules",
      "panda",
      "vanilla-extract",
      "redux",
    ],
    tags: ["frontend-library"],
    maturity: "stable",
  },
  {
    id: "redux",
    logo: "/logos/redux.svg",
    name: "Redux Toolkit",
    slug: "redux",
    category: "frontend-library",
    description: "Structured application state",
    website: "https://redux-toolkit.js.org",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["frontend-library"],
    recommendedFor: [],
    alternatives: [
      "tailwind",
      "css-modules",
      "panda",
      "vanilla-extract",
      "zustand",
    ],
    tags: ["frontend-library"],
    maturity: "stable",
  },
  {
    id: "jotai",
    logo: "/logos/jotai.png",
    name: "Jotai",
    slug: "jotai",
    category: "frontend-library",
    description: "Atomic state management",
    website: "https://jotai.org",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["frontend-library"],
    recommendedFor: [],
    alternatives: [
      "tailwind",
      "css-modules",
      "panda",
      "vanilla-extract",
      "zustand",
    ],
    tags: ["frontend-library"],
    maturity: "stable",
  },
  {
    id: "xstate",
    logo: "/logos/xstate.svg",
    name: "XState",
    slug: "xstate",
    category: "frontend-library",
    description: "State machines and actors",
    website: "https://stately.ai",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["frontend-library"],
    recommendedFor: [],
    alternatives: [
      "tailwind",
      "css-modules",
      "panda",
      "vanilla-extract",
      "zustand",
    ],
    tags: ["frontend-library"],
    maturity: "stable",
  },
  {
    id: "tanstack-query",
    logo: "/logos/tanstack-query.svg",
    name: "TanStack Query",
    slug: "tanstack-query",
    category: "frontend-library",
    description: "Server state, caching and mutations",
    website: "https://tanstack.com/query",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["frontend-library"],
    recommendedFor: [],
    alternatives: [
      "tailwind",
      "css-modules",
      "panda",
      "vanilla-extract",
      "zustand",
    ],
    tags: ["frontend-library"],
    maturity: "stable",
  },
  {
    id: "swr",
    logo: "/logos/swr.svg",
    name: "SWR",
    slug: "swr",
    category: "frontend-library",
    description: "React data-fetching hooks",
    website: "https://swr.vercel.app",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["frontend-library"],
    recommendedFor: [],
    alternatives: [
      "tailwind",
      "css-modules",
      "panda",
      "vanilla-extract",
      "zustand",
    ],
    tags: ["frontend-library"],
    maturity: "stable",
  },
  {
    id: "apollo",
    logo: "/logos/apollo.svg",
    name: "Apollo Client",
    slug: "apollo",
    category: "frontend-library",
    description: "GraphQL client and cache",
    website: "https://apollographql.com",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["frontend-library"],
    recommendedFor: [],
    alternatives: [
      "tailwind",
      "css-modules",
      "panda",
      "vanilla-extract",
      "zustand",
    ],
    tags: ["frontend-library"],
    maturity: "stable",
  },
  {
    id: "urql",
    logo: "/logos/urql.svg",
    name: "urql",
    slug: "urql",
    category: "frontend-library",
    description: "Composable GraphQL client",
    website: "https://urql.dev",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["frontend-library"],
    recommendedFor: [],
    alternatives: [
      "tailwind",
      "css-modules",
      "panda",
      "vanilla-extract",
      "zustand",
    ],
    tags: ["frontend-library"],
    maturity: "stable",
  },
  {
    id: "react-hook-form",
    logo: "/logos/react-hook-form.svg",
    name: "React Hook Form",
    slug: "react-hook-form",
    category: "frontend-library",
    description: "Performant forms with validation",
    website: "https://react-hook-form.com",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["frontend-library"],
    recommendedFor: [],
    alternatives: [
      "tailwind",
      "css-modules",
      "panda",
      "vanilla-extract",
      "zustand",
    ],
    tags: ["frontend-library"],
    maturity: "stable",
  },
  {
    id: "tanstack-form",
    logo: "/logos/tanstack-form.svg",
    name: "TanStack Form",
    slug: "tanstack-form",
    category: "frontend-library",
    description: "Type-safe form state",
    website: "https://tanstack.com/form",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["frontend-library"],
    recommendedFor: [],
    alternatives: [
      "tailwind",
      "css-modules",
      "panda",
      "vanilla-extract",
      "zustand",
    ],
    tags: ["frontend-library"],
    maturity: "stable",
  },
  {
    id: "formik",
    logo: "/logos/formik.svg",
    name: "Formik",
    slug: "formik",
    category: "frontend-library",
    description: "Forms for React applications",
    website: "https://formik.org",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["frontend-library"],
    recommendedFor: [],
    alternatives: [
      "tailwind",
      "css-modules",
      "panda",
      "vanilla-extract",
      "zustand",
    ],
    tags: ["frontend-library"],
    maturity: "stable",
  },
  {
    id: "tanstack-table",
    logo: "/logos/tanstack-table.svg",
    name: "TanStack Table",
    slug: "tanstack-table",
    category: "frontend-library",
    description: "Headless tables and data grids",
    website: "https://tanstack.com/table",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["frontend-library"],
    recommendedFor: [],
    alternatives: [
      "tailwind",
      "css-modules",
      "panda",
      "vanilla-extract",
      "zustand",
    ],
    tags: ["frontend-library"],
    maturity: "stable",
  },
  {
    id: "lucide",
    logo: "/logos/lucide.svg",
    name: "Lucide",
    slug: "lucide",
    category: "frontend-library",
    description: "Consistent open-source icons",
    website: "https://lucide.dev",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["frontend-library"],
    recommendedFor: [],
    alternatives: [
      "tailwind",
      "css-modules",
      "panda",
      "vanilla-extract",
      "zustand",
    ],
    tags: ["frontend-library"],
    maturity: "stable",
  },
];
