import type { Technology } from "@/types/technology";
export const technologies: Technology[] = [
  {
    id: "terraform",
    logo: "/logos/terraform.svg",
    name: "Terraform",
    slug: "terraform",
    category: "infrastructure",
    description: "Declarative infrastructure as code",
    website: "https://terraform.io",
    openSource: false,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["infrastructure"],
    recommendedFor: [],
    alternatives: ["opentofu", "pulumi", "aws-cdk"],
    tags: ["infrastructure"],
    maturity: "stable",
  },
  {
    id: "opentofu",
    logo: "/logos/opentofu.svg",
    name: "OpenTofu",
    slug: "opentofu",
    category: "infrastructure",
    description: "Open-source infrastructure as code",
    website: "https://opentofu.org",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["infrastructure"],
    recommendedFor: [],
    alternatives: ["terraform", "pulumi", "aws-cdk"],
    tags: ["infrastructure"],
    maturity: "stable",
  },
  {
    id: "pulumi",
    logo: "/logos/pulumi.svg",
    name: "Pulumi",
    slug: "pulumi",
    category: "infrastructure",
    description: "Infrastructure using programming languages",
    website: "https://pulumi.com",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["infrastructure"],
    recommendedFor: [],
    alternatives: ["terraform", "opentofu", "aws-cdk"],
    tags: ["infrastructure"],
    maturity: "stable",
  },
  {
    id: "aws-cdk",
    logo: "/logos/aws.svg",
    name: "AWS CDK",
    slug: "aws-cdk",
    category: "infrastructure",
    description: "AWS infrastructure in code",
    website: "https://aws.amazon.com/cdk",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["infrastructure"],
    recommendedFor: [],
    alternatives: ["terraform", "opentofu", "pulumi"],
    tags: ["infrastructure"],
    maturity: "stable",
  },
];
