import type { Technology } from "@/types/technology";
export const technologies: Technology[] = [
  {
    id: "expo",
    logo: "/logos/expo.svg",
    name: "Expo",
    slug: "expo",
    category: "mobile",
    description: "React Native tooling and app delivery",
    website: "https://expo.dev",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["mobile"],
    recommendedFor: [],
    alternatives: ["react-native", "flutter", "capacitor"],
    tags: ["mobile"],
    maturity: "stable",
    implies: ["react-native"],
  },
  {
    id: "react-native",
    logo: "/logos/react-native.svg",
    name: "React Native",
    slug: "react-native",
    category: "mobile",
    description: "Native applications with React",
    website: "https://reactnative.dev",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["mobile"],
    recommendedFor: [],
    alternatives: ["expo", "flutter", "capacitor"],
    tags: ["mobile"],
    maturity: "stable",
  },
  {
    id: "flutter",
    logo: "/logos/flutter.svg",
    name: "Flutter",
    slug: "flutter",
    category: "mobile",
    description: "Cross-platform apps with Dart",
    website: "https://flutter.dev",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["mobile"],
    recommendedFor: [],
    alternatives: ["expo", "react-native", "capacitor"],
    tags: ["mobile"],
    maturity: "stable",
  },
  {
    id: "capacitor",
    logo: "/logos/capacitor.svg",
    name: "Ionic / Capacitor",
    slug: "capacitor",
    category: "mobile",
    description: "Native runtime for web applications",
    website: "https://capacitorjs.com",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["mobile"],
    recommendedFor: [],
    alternatives: ["expo", "react-native", "flutter"],
    tags: ["mobile"],
    maturity: "stable",
  },
];
