import type { Technology } from "@/types/technology";
export const technologies: Technology[] = [
  {
    id: "sentry",
    logo: "/logos/sentry.svg",
    name: "Sentry",
    slug: "sentry",
    category: "monitoring",
    description: "Error tracking and performance insights",
    website: "https://sentry.io",
    openSource: true,
    deployment: {
      saas: true,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["monitoring"],
    recommendedFor: [],
    alternatives: ["glitchtip", "datadog", "newrelic", "signoz", "grafana"],
    tags: ["monitoring"],
    maturity: "stable",
  },
  {
    id: "glitchtip",
    name: "GlitchTip",
    slug: "glitchtip",
    category: "monitoring",
    description: "Open-source error monitoring",
    website: "https://glitchtip.com",
    openSource: true,
    deployment: {
      saas: true,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["monitoring"],
    recommendedFor: [],
    alternatives: ["sentry", "datadog", "newrelic", "signoz", "grafana"],
    tags: ["monitoring"],
    maturity: "stable",
  },
  {
    id: "datadog",
    logo: "/logos/datadog.svg",
    name: "Datadog",
    slug: "datadog",
    category: "monitoring",
    description: "Managed observability platform",
    website: "https://datadoghq.com",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["monitoring"],
    recommendedFor: [],
    alternatives: ["sentry", "glitchtip", "newrelic", "signoz", "grafana"],
    tags: ["monitoring"],
    maturity: "stable",
  },
  {
    id: "newrelic",
    logo: "/logos/newrelic.svg",
    name: "New Relic",
    slug: "newrelic",
    category: "monitoring",
    description: "Application and infrastructure monitoring",
    website: "https://newrelic.com",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["monitoring"],
    recommendedFor: [],
    alternatives: ["sentry", "glitchtip", "datadog", "signoz", "grafana"],
    tags: ["monitoring"],
    maturity: "stable",
  },
  {
    id: "signoz",
    name: "SigNoz",
    slug: "signoz",
    category: "monitoring",
    description: "OpenTelemetry-native observability",
    website: "https://signoz.io",
    openSource: true,
    deployment: {
      saas: true,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["monitoring"],
    recommendedFor: [],
    alternatives: ["sentry", "glitchtip", "datadog", "newrelic", "grafana"],
    tags: ["monitoring"],
    maturity: "stable",
  },
  {
    id: "grafana",
    logo: "/logos/grafana.svg",
    name: "Grafana",
    slug: "grafana",
    category: "monitoring",
    description: "Dashboards, metrics, logs and traces",
    website: "https://grafana.com",
    openSource: true,
    deployment: {
      saas: true,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["monitoring"],
    recommendedFor: [],
    alternatives: ["sentry", "glitchtip", "datadog", "newrelic", "signoz"],
    tags: ["monitoring"],
    maturity: "stable",
  },
];
