import type { Technology } from "@/types/technology";
export const technologies: Technology[] = [
  {
    id: "stripe",
    logo: "/logos/stripe.svg",
    name: "Stripe",
    slug: "stripe",
    category: "payments",
    description: "Payments, billing and subscriptions",
    website: "https://stripe.com",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["payments"],
    recommendedFor: [],
    alternatives: ["paddle", "lemon-squeezy", "adyen", "braintree"],
    tags: ["payments"],
    maturity: "stable",
  },
  {
    id: "paddle",
    logo: "/logos/paddle.svg",
    name: "Paddle",
    slug: "paddle",
    category: "payments",
    description: "Merchant of record for software",
    website: "https://paddle.com",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["payments"],
    recommendedFor: [],
    alternatives: ["stripe", "lemon-squeezy", "adyen", "braintree"],
    tags: ["payments"],
    maturity: "stable",
  },
  {
    id: "lemon-squeezy",
    logo: "/logos/lemon-squeezy.svg",
    name: "Lemon Squeezy",
    slug: "lemon-squeezy",
    category: "payments",
    description: "Digital product payments and tax",
    website: "https://lemonsqueezy.com",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["payments"],
    recommendedFor: [],
    alternatives: ["stripe", "paddle", "adyen", "braintree"],
    tags: ["payments"],
    maturity: "stable",
  },
  {
    id: "adyen",
    logo: "/logos/adyen.svg",
    name: "Adyen",
    slug: "adyen",
    category: "payments",
    description: "Global payment processing",
    website: "https://adyen.com",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["payments"],
    recommendedFor: [],
    alternatives: ["stripe", "paddle", "lemon-squeezy", "braintree"],
    tags: ["payments"],
    maturity: "stable",
  },
  {
    id: "braintree",
    logo: "/logos/braintree.svg",
    name: "Braintree",
    slug: "braintree",
    category: "payments",
    description: "Payment processing from PayPal",
    website: "https://braintreepayments.com",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["payments"],
    recommendedFor: [],
    alternatives: ["stripe", "paddle", "lemon-squeezy", "adyen"],
    tags: ["payments"],
    maturity: "stable",
  },
];
