import type { Technology } from "@/types/technology";
export const technologies: Technology[] = [
  {
    id: "algolia",
    logo: "/logos/algolia.svg",
    name: "Algolia",
    slug: "algolia",
    category: "search",
    description: "Hosted search and discovery",
    website: "https://algolia.com",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["search"],
    recommendedFor: [],
    alternatives: ["typesense", "meilisearch", "opensearch"],
    tags: ["search"],
    maturity: "stable",
  },
  {
    id: "typesense",
    name: "Typesense",
    slug: "typesense",
    category: "search",
    description: "Fast typo-tolerant search",
    website: "https://typesense.org",
    openSource: true,
    deployment: {
      saas: true,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["search"],
    recommendedFor: [],
    alternatives: ["algolia", "meilisearch", "opensearch"],
    tags: ["search"],
    maturity: "stable",
  },
  {
    id: "meilisearch",
    logo: "/logos/meilisearch.svg",
    name: "Meilisearch",
    slug: "meilisearch",
    category: "search",
    description: "Search with instant results",
    website: "https://meilisearch.com",
    openSource: true,
    deployment: {
      saas: true,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["search"],
    recommendedFor: [],
    alternatives: ["algolia", "typesense", "opensearch"],
    tags: ["search"],
    maturity: "stable",
  },
  {
    id: "opensearch",
    logo: "/logos/opensearch.svg",
    name: "OpenSearch",
    slug: "opensearch",
    category: "search",
    description: "Search and analytics engine",
    website: "https://opensearch.org",
    openSource: true,
    deployment: {
      saas: true,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["search"],
    recommendedFor: [],
    alternatives: ["algolia", "typesense", "meilisearch"],
    tags: ["search"],
    maturity: "stable",
  },
];
