import type { Technology } from "@/types/technology";
export const technologies: Technology[] = [
  {
    id: "supabase-storage",
    logo: "/logos/supabase-storage.svg",
    name: "Supabase Storage",
    slug: "supabase-storage",
    category: "storage",
    description: "Object storage with access policies",
    website: "https://supabase.com/storage",
    openSource: true,
    deployment: {
      saas: true,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["storage"],
    recommendedFor: [],
    alternatives: ["s3", "r2", "firebase-storage", "minio"],
    tags: ["storage"],
    maturity: "stable",
    requires: ["supabase"],
  },
  {
    id: "s3",
    name: "Amazon S3",
    slug: "s3",
    category: "storage",
    description: "AWS object storage",
    website: "https://aws.amazon.com/s3",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["storage"],
    recommendedFor: [],
    alternatives: ["supabase-storage", "r2", "firebase-storage", "minio"],
    tags: ["storage"],
    maturity: "stable",
  },
  {
    id: "r2",
    logo: "/logos/r2.svg",
    name: "Cloudflare R2",
    slug: "r2",
    category: "storage",
    description: "S3-compatible object storage",
    website: "https://developers.cloudflare.com/r2",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["storage"],
    recommendedFor: [],
    alternatives: ["supabase-storage", "s3", "firebase-storage", "minio"],
    tags: ["storage"],
    maturity: "stable",
  },
  {
    id: "firebase-storage",
    logo: "/logos/firebase-storage.svg",
    name: "Firebase Storage",
    slug: "firebase-storage",
    category: "storage",
    description: "Managed object storage for Firebase",
    website: "https://firebase.google.com/docs/storage",
    openSource: false,
    deployment: {
      saas: true,
      selfHosted: false,
      local: false,
      browser: false,
    },
    capabilities: ["storage"],
    recommendedFor: [],
    alternatives: ["supabase-storage", "s3", "r2", "minio"],
    tags: ["storage"],
    maturity: "stable",
    requires: ["firebase"],
  },
  {
    id: "minio",
    logo: "/logos/minio.svg",
    name: "MinIO",
    slug: "minio",
    category: "storage",
    description: "Self-hosted S3-compatible object storage",
    website: "https://min.io",
    openSource: false,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["storage"],
    recommendedFor: [],
    alternatives: ["supabase-storage", "s3", "r2", "firebase-storage"],
    tags: ["storage"],
    maturity: "stable",
  },
];
