import type { Technology } from "@/types/technology";
export const technologies: Technology[] = [
  {
    id: "shadcn",
    logo: "/logos/shadcn.svg",
    name: "shadcn/ui",
    slug: "shadcn",
    category: "ui",
    description: "Composable components you own",
    website: "https://ui.shadcn.com",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["ui"],
    recommendedFor: [],
    alternatives: ["base-ui", "radix", "mui", "mantine", "chakra"],
    tags: ["ui"],
    maturity: "stable",
    requires: ["tailwind"],
  },
  {
    id: "base-ui",
    logo: "/logos/base-ui.svg",
    name: "Base UI",
    slug: "base-ui",
    category: "ui",
    description: "Accessible unstyled React primitives",
    website: "https://base-ui.com",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["ui"],
    recommendedFor: [],
    alternatives: ["shadcn", "radix", "mui", "mantine", "chakra"],
    tags: ["ui"],
    maturity: "stable",
  },
  {
    id: "radix",
    name: "Radix UI",
    slug: "radix",
    category: "ui",
    description: "Accessible React primitives",
    website: "https://radix-ui.com",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["ui"],
    recommendedFor: [],
    alternatives: ["shadcn", "base-ui", "mui", "mantine", "chakra"],
    tags: ["ui"],
    maturity: "stable",
  },
  {
    id: "mui",
    logo: "/logos/mui.svg",
    name: "MUI",
    slug: "mui",
    category: "ui",
    description: "Material Design React components",
    website: "https://mui.com",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["ui"],
    recommendedFor: [],
    alternatives: ["shadcn", "base-ui", "radix", "mantine", "chakra"],
    tags: ["ui"],
    maturity: "stable",
  },
  {
    id: "mantine",
    logo: "/logos/mantine.svg",
    name: "Mantine",
    slug: "mantine",
    category: "ui",
    description: "React components and hooks",
    website: "https://mantine.dev",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["ui"],
    recommendedFor: [],
    alternatives: ["shadcn", "base-ui", "radix", "mui", "chakra"],
    tags: ["ui"],
    maturity: "stable",
  },
  {
    id: "chakra",
    logo: "/logos/chakra.svg",
    name: "Chakra UI",
    slug: "chakra",
    category: "ui",
    description: "Accessible React component system",
    website: "https://chakra-ui.com",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["ui"],
    recommendedFor: [],
    alternatives: ["shadcn", "base-ui", "radix", "mui", "mantine"],
    tags: ["ui"],
    maturity: "stable",
  },
  {
    id: "antd",
    logo: "/logos/antd.svg",
    name: "Ant Design",
    slug: "antd",
    category: "ui",
    description: "Enterprise React component library",
    website: "https://ant.design",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["ui"],
    recommendedFor: [],
    alternatives: ["shadcn", "base-ui", "radix", "mui", "mantine"],
    tags: ["ui"],
    maturity: "stable",
  },
  {
    id: "heroui",
    logo: "/logos/heroui.svg",
    name: "HeroUI",
    slug: "heroui",
    category: "ui",
    description: "Modern React component library",
    website: "https://heroui.com",
    openSource: true,
    deployment: {
      saas: false,
      selfHosted: true,
      local: true,
      browser: false,
    },
    capabilities: ["ui"],
    recommendedFor: [],
    alternatives: ["shadcn", "base-ui", "radix", "mui", "mantine"],
    tags: ["ui"],
    maturity: "stable",
  },
];
